include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true
  exclude:
    - lib/generated_plugin_registrant.dart
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    close_sinks: true
    sort_constructors_first: true
