include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: true
    always_use_package_imports: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore
    use_setters_to_change_properties: ignore
