name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.16.2
homepage: https://github.com/fluttercommunity/chewie

environment:
  sdk: '>=3.12.0 <4.0.0'
  flutter: ">=3.44.0"

dependencies:
  cupertino_icons: ^1.0.9
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  video_player: ^2.14.0
  wakelock_plus: ^1.8.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  video_player_platform_interface: ^6.9.0

flutter:
  uses-material-design: true
