name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.13.1
homepage: https://github.com/fluttercommunity/chewie

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: ">=3.41.0"

dependencies:
  cupertino_icons: ^1.0.9
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  video_player: ^2.11.1
  wakelock_plus: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
